'use client';
import { useEffect,useId,useState } from 'react';
import type { Editor } from '@tiptap/core';
import { AlignLeft,AlignCenter,AlignRight,AlignJustify,IndentIncrease,IndentDecrease,ListOrdered,Pilcrow,Table2,Type,Strikethrough,Superscript,Subscript,Highlighter,RemoveFormatting,Omega } from 'lucide-react';
import { IconButton,Popover } from './primitives';
import { fontSizes,validFontSize } from '@/lib/editor-preferences';
import styles from './editor-tools.module.css';

export function FontSizeInput({size,onChange}:{size:number;onChange:(size:number)=>void}){
  const [value,setValue]=useState(String(size)),id=useId();useEffect(()=>setValue(String(size)),[size]);
  function commit(){const n=Number(value);if(validFontSize(n))onChange(n);else setValue(String(size));}
  return <span className={styles.size}><input aria-label="본문 크기" title="본문 크기 · 10–72px" type="number" min={10} max={72} step={0.5} list={id} value={value} onChange={e=>{setValue(e.target.value);const n=Number(e.target.value);if(validFontSize(n))onChange(n);}} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur();}}}/><span>px</span><datalist id={id}>{fontSizes.map(n=><option key={n} value={n}/>)}</datalist></span>;
}
const symbols=[{name:'문장 부호',characters:['“','”','‘','’','「','」','『','』','〈','〉','《','》','…','—','–','·','※']},{name:'SF · 수학',characters:['±','×','÷','≠','≤','≥','≈','∞','√','∑','∫','°','℃','α','β','γ','δ','λ','μ','π','Ω']},{name:'화살표 · 기호',characters:['←','→','↑','↓','↔','⇒','⇔','☐','☑','○','●','◇','◆','☆','★']}];
export function EditorFormatTools({editor,readonly}:{editor:Editor|null;readonly:boolean}){
  const [panel,setPanel]=useState<string|null>(null),[rows,setRows]=useState(3),[cols,setCols]=useState(3),[header,setHeader]=useState(true);
  const disabled=!editor||readonly;
  const attrs=editor?.getAttributes(editor.isActive('heading')?'heading':'paragraph')||{};
  function paragraph(patch:Record<string,unknown>){if(!editor||readonly)return;editor.chain().focus().updateAttributes('paragraph',patch).updateAttributes('heading',patch).run();setPanel(null);}
  function indent(direction:number){if(!editor||readonly)return;if(editor.isActive('listItem')){const chain=editor.chain().focus();if(direction>0)chain.sinkListItem('listItem').run();else chain.liftListItem('listItem').run();}else paragraph({indent:Math.max(0,Math.min(8,Number(attrs.indent||0)+direction))});}
  const buttons=[{id:'marks',label:'문자 서식',icon:<Type size={16}/>},{id:'paragraph',label:'문단 서식',icon:<Pilcrow size={16}/>},{id:'table',label:'표',icon:<Table2 size={16}/>},{id:'symbols',label:'특수문자',icon:<Omega size={16}/>}];
  const actions=[['위에 행 추가',()=>editor?.chain().focus().addRowBefore().run(),()=>editor?.can().addRowBefore()],['아래에 행 추가',()=>editor?.chain().focus().addRowAfter().run(),()=>editor?.can().addRowAfter()],['왼쪽 열 추가',()=>editor?.chain().focus().addColumnBefore().run(),()=>editor?.can().addColumnBefore()],['오른쪽 열 추가',()=>editor?.chain().focus().addColumnAfter().run(),()=>editor?.can().addColumnAfter()],['행 삭제',()=>editor?.chain().focus().deleteRow().run(),()=>editor?.can().deleteRow()],['열 삭제',()=>editor?.chain().focus().deleteColumn().run(),()=>editor?.can().deleteColumn()],['셀 병합',()=>editor?.chain().focus().mergeCells().run(),()=>editor?.can().mergeCells()],['셀 나누기',()=>editor?.chain().focus().splitCell().run(),()=>editor?.can().splitCell()],['제목 행 전환',()=>editor?.chain().focus().toggleHeaderRow().run(),()=>editor?.can().toggleHeaderRow()],['표 삭제',()=>editor?.chain().focus().deleteTable().run(),()=>editor?.can().deleteTable()]] as const;
  return <><select aria-label="문단 스타일" value={editor?.isActive('heading')?String(editor.getAttributes('heading').level):'body'} disabled={disabled} onChange={e=>{if(e.target.value==='body')editor?.chain().focus().setParagraph().run();else editor?.chain().focus().setHeading({level:Number(e.target.value) as 1|2|3}).run();}}><option value="body">본문</option>{[1,2,3].map(level=><option key={level} value={level}>제목 {level}</option>)}</select>{buttons.map(item=><Popover key={item.id} open={panel===item.id} onOpenChange={open=>setPanel(open?item.id:null)} title={item.label} initialFocus={['marks','paragraph'].includes(item.id)?'content':undefined} width={item.id==='symbols'?340:300} onReturnFocus={()=>editor?.commands.focus()} trigger={<IconButton label={item.label} disabled={disabled} aria-pressed={panel===item.id}>{item.icon}</IconButton>}>
    <div className={styles.tools}>
    {item.id==='marks'&&<div className={styles.row}>
      <IconButton label="취소선" aria-pressed={editor?.isActive('strike')} onClick={()=>{editor?.chain().focus().toggleStrike().run();setPanel(null);}}><Strikethrough size={16}/></IconButton>
      <IconButton label="위첨자" aria-pressed={editor?.isActive('superscript')} onClick={()=>{editor?.chain().focus().toggleSuperscript().run();setPanel(null);}}><Superscript size={16}/></IconButton>
      <IconButton label="아래첨자" aria-pressed={editor?.isActive('subscript')} onClick={()=>{editor?.chain().focus().toggleSubscript().run();setPanel(null);}}><Subscript size={16}/></IconButton>
      <IconButton label="강조 표시" aria-pressed={editor?.isActive('highlight')} onClick={()=>{editor?.chain().focus().toggleHighlight().run();setPanel(null);}}><Highlighter size={16}/></IconButton>
      <IconButton label="문자 서식 지우기" onClick={()=>{let chain=editor?.chain().focus();for(const name of ['bold','italic','underline','strike','code','superscript','subscript','highlight'])chain=chain?.unsetMark(name);chain?.run();setPanel(null);}}><RemoveFormatting size={16}/></IconButton>
    </div>}
    {item.id==='paragraph'&&<><div className={styles.row}>{[{name:'왼쪽 정렬',value:'left',icon:<AlignLeft size={16}/>},{name:'가운데 정렬',value:'center',icon:<AlignCenter size={16}/>},{name:'오른쪽 정렬',value:'right',icon:<AlignRight size={16}/>},{name:'양쪽 정렬',value:'justify',icon:<AlignJustify size={16}/>}].map(align=><IconButton key={align.value} label={align.name} aria-pressed={editor?.isActive({textAlign:align.value})} onClick={()=>paragraph({textAlign:align.value})}>{align.icon}</IconButton>)}<IconButton label="들여쓰기" onClick={()=>indent(1)}><IndentIncrease size={16}/></IconButton><IconButton label="내어쓰기" onClick={()=>indent(-1)}><IndentDecrease size={16}/></IconButton><IconButton label="번호 목록" aria-pressed={editor?.isActive('orderedList')} onClick={()=>{editor?.chain().focus().toggleOrderedList().run();setPanel(null);}}><ListOrdered size={16}/></IconButton></div>
      <label>줄간격<select aria-label="줄간격" value={attrs.lineHeight??'default'} onChange={e=>paragraph({lineHeight:e.target.value==='default'?null:Number(e.target.value)})}><option value="default">기본 · 2배</option>{[1,1.15,1.3,1.5,1.75,2,2.25,2.5,3].map(n=><option key={n} value={n}>{n}배</option>)}</select></label>
      <label>첫 줄 들여쓰기<select aria-label="첫 줄 들여쓰기" value={attrs.firstLineIndent??'default'} onChange={e=>paragraph({firstLineIndent:e.target.value==='default'?null:Number(e.target.value)})}><option value="default">기본</option>{[0,1,2,3,4].map(n=><option key={n} value={n}>{n}자</option>)}</select></label>
      <div className={styles.grid}>{[['문단 앞 간격','spaceBefore'],['문단 뒤 간격','spaceAfter']].map(([label,key])=><label key={key}>{label}<select aria-label={label} value={attrs[key]??'default'} onChange={e=>paragraph({[key]:e.target.value==='default'?null:Number(e.target.value)})}><option value="default">기본</option>{[0,4,8,12,16,24,36,48].map(n=><option key={n} value={n}>{n}px</option>)}</select></label>)}</div><button className="button" onClick={()=>paragraph({lineHeight:null,indent:null,firstLineIndent:null,spaceBefore:null,spaceAfter:null,textAlign:null})}>문단 서식 초기화</button></>}
    {item.id==='table'&&(editor?.isActive('table')?<div className={styles.actions}>{actions.map(([label,run,can])=><button key={label} className="button" disabled={!can()} onClick={()=>{run();setPanel(null);}}>{label}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();if(!editor||readonly||!Number.isInteger(rows)||!Number.isInteger(cols)||rows<1||rows>20||cols<1||cols>12)return;editor.chain().focus().insertTable({rows,cols,withHeaderRow:header}).run();setPanel(null);}}><div className={styles.grid}><label>행<input aria-label="표 행 수" type="number" value={rows} min={1} max={20} onChange={e=>setRows(Number(e.target.value))}/></label><label>열<input aria-label="표 열 수" type="number" value={cols} min={1} max={12} onChange={e=>setCols(Number(e.target.value))}/></label></div><label className={styles.check}><input type="checkbox" checked={header} onChange={e=>setHeader(e.target.checked)}/>제목 행</label><div className="popover-actions"><button className="button" type="submit">표 삽입</button></div></form>)}
    {item.id==='symbols'&&symbols.map(group=><div key={group.name}><p className={styles.group}>{group.name}</p><div className={styles.symbols}>{group.characters.map(char=><button key={char} className="button" aria-label={`특수문자 ${char}`} onClick={()=>{if(!editor||readonly)return;editor.view.dispatch(editor.state.tr.insertText(char));setPanel(null);}}>{char}</button>)}</div></div>)}
    </div>
  </Popover>)}</>;
}
