'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { BookOpen, Files, Search, LayoutGrid, Archive, Globe2, PanelRightClose, PanelLeftClose, Columns2, Maximize2, Plus, FileText, ChevronDown, ChevronRight, X, Link2, Save, CloudOff, NotebookPen, Paperclip, Settings2, ArrowLeftRight } from 'lucide-react';
import { useStudio } from './studio-provider';
import { TooltipProvider, IconButton, Modal } from './primitives';
import { RichEditor } from './rich-editor';
import { NovelDocument, newDocument, plainText, statuses, wikiReferences } from '@/lib/model';
import { cloudConfigured, cloud } from '@/lib/cloud';
import { db } from '@/lib/database';
import { AIReview } from './ai-review';

export function Studio(){
  const s=useStudio();const [workId,setWorkId]=useState('');const [activeId,setActiveId]=useState('');const [tabs,setTabs]=useState<string[]>([]);
  const [splitId,setSplitId]=useState<string|null>(null);const [focus,setFocus]=useState(false);const [explorer,setExplorer]=useState(true);const [inspector,setInspector]=useState(true);
  const [query,setQuery]=useState('');const [panel,setPanel]=useState<'details'|'links'|'ai'>('details');const [section,setSection]=useState<'documents'|'board'>('documents');const [collapsed,setCollapsed]=useState<string[]>([]);
  const [splitWidth,setSplitWidth]=useState(50);const [mobileInspector,setMobileInspector]=useState(false);const [workSettings,setWorkSettings]=useState(false);
  useEffect(()=>{if(window.innerWidth<700)setExplorer(false);if(window.innerWidth<900)setInspector(false);},[]);
  if(s.loading)return <div className="loading-screen"><NotebookPen size={28}/><p>집필실을 여는 중입니다.</p></div>;
  if(!s.canUse)return <Login/>;
  if(!s.state)return <div className="loading-screen">원고를 불러오지 못했습니다. {s.error}</div>;
  const work=s.state.works.find(w=>w.id===workId)||s.state.works[0];
  const active=work.documents.find(d=>d.id===activeId)||work.documents.find(d=>d.kind==='scene')||work.documents[0];
  const openTabs=[...new Set([...(tabs.length?tabs:[active.id]),active.id])].filter(id=>work.documents.some(d=>d.id===id));
  const split=work.documents.find(d=>d.id===splitId);
  function openDoc(id:string,beside=false){if(beside){setSplitId(id===active.id?null:id);return;}if(id===splitId)setSplitId(active.id);setActiveId(id);setTabs(t=>[...new Set([...t,id])]);setSection('documents');}
  function patchDoc(id:string,patch:Partial<NovelDocument>){s.update(state=>({...state,works:state.works.map(w=>w.id===work.id?{...w,documents:w.documents.map(d=>d.id===id?{...d,...patch,updatedAt:new Date().toISOString()}:d)}:w)}));}
  function createDoc(kind:NovelDocument['kind']){const d=newDocument(kind,kind==='scene'?'새 장면':kind==='wiki'?'새 설정':'새 메모');s.update(state=>({...state,works:state.works.map(w=>w.id===work.id?{...w,documents:[...w.documents,d]}:w)}));openDoc(d.id);}
  function moveDoc(direction:number){const ids=work.documents.filter(d=>d.kind===active.kind).map(d=>d.id);const index=ids.indexOf(active.id);const next=ids[index+direction];if(!next)return;s.update(state=>({...state,works:state.works.map(w=>{if(w.id!==work.id)return w;const docs=[...w.documents];const a=docs.findIndex(d=>d.id===active.id),b=docs.findIndex(d=>d.id===next);[docs[a],docs[b]]=[docs[b],docs[a]];return{...w,documents:docs};})}));}
  async function downloadAsset(id:string){try{const meta=s.state!.assets.find(a=>a.id===id)!;let blob=(await db.assets.get([s.namespace,id]))?.blob;if(!blob&&cloudConfigured){const result=await cloud().storage.from('private-assets').download(`${s.user}/${id}`);if(result.error)throw result.error;blob=result.data||undefined;}if(!blob)throw new Error('첨부를 찾지 못했습니다.');const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=meta.name;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}catch(e){alert(e instanceof Error?e.message:'첨부를 열지 못했습니다.');}}
  const visible=work.documents.filter(d=>!query||`${d.title} ${plainText(d.content)}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const backlinks=work.documents.filter(d=>wikiReferences(d.content).includes(active.id));
  const count=plainText(active.content).replace(/\s/g,'').length;
  return <TooltipProvider><div className={`studio ${focus?'focus-mode':''}`}>
    <header className="studio-header"><Link className="brand" href="/library"><BookOpen size={20}/><strong>궤도 서재</strong></Link><span className="header-divider"/><div className="work-picker-actions"><select aria-label="작품 선택" className="work-picker" value={work.id} onChange={e=>{setWorkId(e.target.value);setActiveId('');setTabs([]);setSplitId(null);}}>{s.state.works.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select><IconButton label="새 작품 만들기" onClick={()=>window.dispatchEvent(new CustomEvent('studio-modal',{detail:'new-work'}))}><Plus size={15}/></IconButton><IconButton label="작품 정보 편집" onClick={()=>setWorkSettings(true)}><Settings2 size={15}/></IconButton></div><span className="work-form">{work.form}</span>
      <div className="header-end"><span className="connection"><CloudOff size={14}/>{cloudConfigured?'작가 계정':'기기 저장 · 클라우드 미연결'}</span><Link className="button ghost" href="/library"><Globe2 size={15}/>공개 서재</Link><button className="primary" onClick={()=>window.dispatchEvent(new CustomEvent('studio-modal',{detail:'publish'}))}>게시 준비</button></div>
    </header>
    <div className="studio-body">
      <nav className="activity-rail" aria-label="집필 도구"><IconButton label="원고와 설정" aria-pressed={section==='documents'} onClick={()=>{setSection('documents');setExplorer(v=>!v);}}><Files size={22}/></IconButton><IconButton label="작품 검색" onClick={()=>{setExplorer(true);setFocus(false);setTimeout(()=>document.getElementById('workspace-search')?.focus(),50);}}><Search size={22}/></IconButton><IconButton label="장면 보드" aria-pressed={section==='board'} onClick={()=>setSection('board')}><LayoutGrid size={22}/></IconButton><span className="rail-space"/><IconButton label="문서 가져오기 · 내보내기" onClick={()=>window.dispatchEvent(new CustomEvent('studio-modal',{detail:'interchange'}))}><ArrowLeftRight size={22}/></IconButton><IconButton label="백업과 복구" onClick={()=>window.dispatchEvent(new CustomEvent('studio-modal',{detail:'backup'}))}><Archive size={22}/></IconButton></nav>
      {explorer&&!focus&&<aside className="explorer"><div className="explorer-title"><strong>작업 공간</strong><IconButton label="탐색기 접기" onClick={()=>setExplorer(false)}><PanelLeftClose size={16}/></IconButton></div><div className="search-field"><Search size={15}/><input id="workspace-search" aria-label="작품 내 검색" placeholder="작품 안에서 찾기" value={query} onChange={e=>setQuery(e.target.value)}/></div>
        {(['scene','wiki','memo'] as const).map(kind=>{const label=kind==='scene'?'원고':kind==='wiki'?'설정집':'메모 · 리서치';const closed=collapsed.includes(kind);return <section className="tree-group" key={kind}><div className="tree-heading"><button onClick={()=>setCollapsed(c=>c.includes(kind)?c.filter(v=>v!==kind):[...c,kind])}>{closed?<ChevronRight size={14}/>:<ChevronDown size={14}/>}<strong>{label}</strong><span>{work.documents.filter(d=>d.kind===kind).length}</span></button><IconButton label={`${label} 추가`} onClick={()=>createDoc(kind)}><Plus size={15}/></IconButton></div>{!closed&&visible.filter(d=>d.kind===kind).map((d,i)=><div key={d.id}><div className={`tree-row ${active.id===d.id?'selected':''}`}><button onClick={()=>openDoc(d.id)}><FileText size={15}/><span>{d.title}</span>{d.kind==='scene'&&<i className={`status-marker ${d.status}`} aria-label={statuses[d.status]}/>}</button><IconButton label={`${d.title} 옆에서 열기`} onClick={()=>openDoc(d.id,true)}><Columns2 size={14}/></IconButton></div>{d.kind==='scene'&&(i===0||work.documents[i-1]?.chapter!==d.chapter)&&<div className="tree-meta">{d.chapter}</div>}</div>)}</section>;})}
        {query&&!visible.length&&<p className="empty-text">검색 결과가 없습니다.</p>}<div className="explorer-bottom"><span>{work.documents.filter(d=>d.kind==='scene').length}개 장면</span><span>{work.documents.filter(d=>d.kind==='scene').reduce((n,d)=>n+plainText(d.content).replace(/\s/g,'').length,0).toLocaleString()}자</span></div>
      </aside>}
      <main className="workspace-main"><div className="workspace-tabs" role="tablist" aria-label="열린 문서">{openTabs.map(id=>{const d=work.documents.find(d=>d.id===id)!;return <div className={`doc-tab ${id===active.id?'active':''}`} key={id}><button role="tab" aria-selected={id===active.id} onClick={()=>openDoc(id)}><FileText size={14}/>{d.title}</button>{openTabs.length>1&&<button aria-label={`${d.title} 탭 닫기`} onClick={()=>{const remaining=openTabs.filter(v=>v!==id);setTabs(remaining);if(id===active.id)setActiveId(remaining[0]);}}><X size={13}/></button>}</div>;})}<div className="tab-spacer"/><IconButton label="분할 편집" aria-pressed={!!split} onClick={()=>setSplitId(split?null:work.documents.find(d=>d.kind==='wiki'&&d.id!==active.id)?.id||null)}><Columns2 size={16}/></IconButton><IconButton label="집중 모드" aria-pressed={focus} onClick={()=>setFocus(v=>!v)}><Maximize2 size={16}/></IconButton><IconButton label="참고 패널" aria-pressed={inspector} onClick={()=>{if(window.innerWidth<900)setMobileInspector(v=>!v);setInspector(v=>!v);}}><PanelRightClose size={16}/></IconButton></div>
        <div className="breadcrumb"><span>{work.title}</span><span>/</span><span>{active.kind==='scene'?'원고':active.kind==='wiki'?'설정집':'메모'}</span><span>/</span><strong>{active.title}</strong><span className="breadcrumb-end">{statuses[active.status]}</span></div>
        {section==='board'?<div className="scene-board"><div className="board-title"><h1>장면 보드</h1><button className="button" onClick={()=>createDoc('scene')}><Plus size={16}/>장면 추가</button></div>{(['idea','draft','review','done'] as const).map(status=><section className="board-column" key={status}><h2>{statuses[status]} <small>{work.documents.filter(d=>d.kind==='scene'&&d.status===status).length}</small></h2>{work.documents.filter(d=>d.kind==='scene'&&d.status===status).map(d=><button className="scene-card" key={d.id} onClick={()=>openDoc(d.id)}><small>{d.chapter}</small><strong>{d.title}</strong><p>{d.summary||'장면 요약을 작성해보세요.'}</p><footer>{d.pov||'시점 미정'}<span>{d.storyTime}</span></footer></button>)}</section>)}</div>:<div className={`editor-panes ${split?'is-split':''}`} style={{'--split-percent':`${splitWidth}%`} as React.CSSProperties}><RichEditor key={`${active.id}-${s.epoch}`} doc={active} onChange={content=>patchDoc(active.id,{content})} wiki={work.documents.filter(d=>d.kind==='wiki')} onWikiClick={id=>openDoc(id,true)} readonly={!!s.conflict}/>{split&&<><div className="split-divider resize-handle" role="separator" aria-label="분할 편집 폭" aria-orientation="vertical" aria-valuenow={splitWidth} aria-valuemin={30} aria-valuemax={70} tabIndex={0} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(e.buttons){const rect=e.currentTarget.parentElement!.getBoundingClientRect();setSplitWidth(Math.max(30,Math.min(70,(e.clientX-rect.left)/rect.width*100)));}}} onKeyDown={e=>{if(e.key==='ArrowLeft')setSplitWidth(v=>Math.max(30,v-2));if(e.key==='ArrowRight')setSplitWidth(v=>Math.min(70,v+2));}}/><div className="split-pane"><div className="split-heading"><span>참고 · {split.title}</span><IconButton label="분할 닫기" onClick={()=>setSplitId(null)}><X size={16}/></IconButton></div><RichEditor key={`${split.id}-${s.epoch}`} doc={split} onChange={content=>patchDoc(split.id,{content})} wiki={work.documents.filter(d=>d.kind==='wiki')} onWikiClick={id=>openDoc(id,true)} readonly={!!s.conflict}/></div></>}</div>}
      </main>
      {inspector&&!focus&&<aside className={`inspector ${mobileInspector?'inspector-mobile-open':''}`} ><div className="inspector-tabs">{(['details','links','ai'] as const).map(p=><button className={panel===p?'active':''} key={p} onClick={()=>setPanel(p)}>{p==='details'?'문서 정보':p==='links'?'참고':'AI'}</button>)}</div><div className="inspector-content">
        {panel==='details'?<><span className="eyebrow">{active.kind==='scene'?'SCENE':active.kind==='wiki'?'WORLD BIBLE':'NOTES'}</span><label>제목<input value={active.title} onChange={e=>{if(e.target.value)patchDoc(active.id,{title:e.target.value});}}/></label><label>진행 상태<select value={active.status} onChange={e=>patchDoc(active.id,{status:e.target.value as NovelDocument['status']})}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
          {active.kind==='scene'?<><label>부 · 장<input value={active.chapter} onChange={e=>patchDoc(active.id,{chapter:e.target.value})}/></label><label>시점 인물<input value={active.pov} onChange={e=>patchDoc(active.id,{pov:e.target.value})}/></label><label>작중 시간<input value={active.storyTime} onChange={e=>patchDoc(active.id,{storyTime:e.target.value})}/></label><label>장면 요약<textarea value={active.summary} rows={4} onChange={e=>patchDoc(active.id,{summary:e.target.value})}/></label></>:active.kind==='wiki'?<><label>분류<input value={active.category} onChange={e=>patchDoc(active.id,{category:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={active.isPublic} onChange={e=>patchDoc(active.id,{isPublic:e.target.checked})}/>독자용 설명 공개</label><label>독자용 설명<textarea rows={5} value={active.publicSummary} onChange={e=>patchDoc(active.id,{publicSummary:e.target.value})}/></label><p className="field-help">집필용 본문과 별도로 게시됩니다.</p></>:null}
          <div className="doc-order"><button onClick={()=>moveDoc(-1)}>순서 올리기</button><button onClick={()=>moveDoc(1)}>순서 내리기</button></div><div className="inspector-section"><h3>첨부 자료</h3><div className="asset-list">{active.assetIds.map(id=><button key={id} onClick={()=>void downloadAsset(id)}><Paperclip size={14}/>{s.state!.assets.find(a=>a.id===id)?.name}</button>)}</div><label className="asset-upload">이미지 첨부<input aria-label="이미지 첨부" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void s.addAsset(work.id,active.id,file).catch(error=>alert(error.message));e.target.value='';}}/></label></div><div className="inspector-section"><h3>복구 지점</h3><button className="button full" onClick={()=>void s.snapshot(`${active.title} · 수동 저장`).catch(e=>alert(e.message))}><Save size={15}/>현재 원고 보관</button></div>
        </>:panel==='links'?<><h3>연결된 설정</h3>{wikiReferences(active.content).map(id=>work.documents.find(d=>d.id===id)).filter(Boolean).map(d=><button className="reference-card" key={d!.id} onClick={()=>openDoc(d!.id,true)}><Link2 size={15}/><span><strong>{d!.title}</strong><small>{d!.category}</small></span></button>)}<h3>이 문서를 참조하는 원고</h3>{backlinks.length?backlinks.map(d=><button className="reference-card" key={d.id} onClick={()=>openDoc(d.id)}><FileText size={15}/>{d.title}</button>):<p className="muted">아직 참조가 없습니다.</p>}</>:<div className="ai-intro"><h3>작품 자료 찾기</h3><p>설정 문서와 원고에서 필요한 내용을 찾아보세요.</p><input aria-label="AI 자료 검색" placeholder="인물, 기술, 장소" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&visible.map(d=><button key={d.id} className="reference-card" onClick={()=>openDoc(d.id,true)}><FileText size={15}/>{d.title}</button>)}<AIReview workId={work.id} doc={active} onChange={content=>patchDoc(active.id,{content})} onOpen={id=>openDoc(id,true)}/></div>}
      </div></aside>}
    </div>
    <footer className="studio-status" aria-live="polite"><span>{s.status}</span>{s.error&&<button className="status-error" onClick={s.clearError}>{s.error}</button>}<div><span>{count.toLocaleString()}자 · 공백 제외</span><span>{active.pov||'시점 미지정'}</span><span>{work.form}</span></div></footer>
    <StudioDialogs workId={work.id}/><Modal open={workSettings} onClose={()=>setWorkSettings(false)} title="작품 정보"><div className="form-grid"><label>작품명<input value={work.title} onChange={e=>{if(e.target.value)s.update(state=>({...state,works:state.works.map(w=>w.id===work.id?{...w,title:e.target.value}:w)}));}}/></label><label>부제<input value={work.subtitle} onChange={e=>s.update(state=>({...state,works:state.works.map(w=>w.id===work.id?{...w,subtitle:e.target.value}:w)}))}/></label><label>작품 소개<textarea rows={4} value={work.description} onChange={e=>s.update(state=>({...state,works:state.works.map(w=>w.id===work.id?{...w,description:e.target.value}:w)}))}/></label></div></Modal>
  </div></TooltipProvider>;
}
function Login(){
  const s=useStudio();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  return <div className="login-screen"><BookOpen size={30}/><h1>궤도 서재 집필실</h1>{cloudConfigured?<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await s.login(email,password);}catch(e){setError(e instanceof Error?e.message:'로그인 실패');}finally{setBusy(false);}}}><label>이메일<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>비밀번호<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>집필실 열기</button>{error&&<p role="alert">{error}</p>}</form>:<p>작가용 클라우드 연결을 설정한 뒤 이용할 수 있습니다.</p>}<Link href="/library">공개 서재</Link></div>;
}
// The dialog module is kept separate from the writing surface.
import { StudioDialogs } from './studio-dialogs';
